name: quotify_utils
description: Utilities for the quotify project
version: 4.1.0
publish_to: 'none'

environment:
  sdk: ^3.7.0

resolution: workspace

dependencies:
  event: ^3.1.0
  logging: ^1.3.0
  meta: ^1.15.0

dev_dependencies:
  checks: ^0.3.0
  lint: ^2.8.0
  test: ^1.25.8
