name: quotify_utils
description: Utilities for the quotify project
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ^3.6.0

resolution: workspace

dependencies:
  meta: ^1.15.0

dev_dependencies:
  checks: ^0.3.0
  test: ^1.25.8
