name: quotify
description: The new and refactored version of the uncompleted My Quotes app.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

workspace:
  - packages/quotify_utils
  - packages/services/shared_preferences_service
  - packages/services/flutter_secure_storage_service
  - packages/services/shared_preferences_service_test
  - packages/services/drift_database_service
  - packages/theme_brightness_repository
  - packages/primary_colors_repository
  - packages/languages_repository
  - packages/privacy_repository
  - packages/quotes_repository
  - packages/tags_repository
  - packages/backup_repository

dependencies:
  flutter:
    sdk: flutter
  languages_repository: ^0.0.1
  logging: ^1.3.0
  primary_colors_repository: ^0.0.1
  privacy_repository: ^1.0.0
  pub_semver: ^2.1.5
  quotes_repository: ^1.0.0
  quotify_utils: ^3.0.0
  shared_preferences_service: ^1.0.0
  tags_repository: ^1.0.0
  theme_brightness_repository: ^0.0.1

dev_dependencies:
  dependency_validator: ^4.1.2
  faker: ^2.2.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mocktail: ^1.0.4
  shared_preferences_service_test: ^0.0.1
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true
