name: quotify
description: The new and refactored version of the uncompleted My Quotes app.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  get_it: ^8.0.2
  go_router: ^14.6.1
  logging: ^1.3.0
  meta: ^1.15.0
  pub_semver: ^2.1.4
  shared_preferences: ^2.3.3

dev_dependencies:
  dependency_validator: ^4.1.1
  faker: ^2.2.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
