version: '3'

tasks:
  clean-get:
    cmds:
      - flutter clean
      - flutter pub get
  pub-deep-upgrade:
    cmds:
      - cmd: pwsh -Command Remove-Item pubspec.lock
        platforms:
          - windows
      - flutter clean
      - flutter pub upgrade --major-versions
