name: tags_repository
description: "A new Flutter package project."
version: 0.0.1

resolution: workspace

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  quotify_utils: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^7.0.0
