name: backup_logic
description: Logic layer for the backup feature
version: 0.0.1

resolution: workspace

environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

dependencies:
  collection: ^1.19.1
  cross_file: ^0.3.4+2
  cryptography: ^2.7.0
  encrypt: ^5.0.3
  flutter:
    sdk: flutter
  languages_repository: ^0.0.1
  meta: ^1.16.0
  mocktail: ^1.0.4
  primary_colors_repository: ^0.0.1
  privacy_repository: ^1.0.0
  quotes_repository: ^1.0.1
  quotify_utils: ^4.0.0
  share_plus: ^10.1.4
  tags_repository: ^1.0.0
  theme_brightness_repository: ^0.0.1

dev_dependencies:
  faker: ^2.2.0
  flutter_test:
    sdk: flutter
  path_provider_platform_interface: ^2.1.2
  plugin_platform_interface: ^2.1.8
  very_good_analysis: ^7.0.0
