name: privacy_repository
description: "A new Flutter package project."
version: 1.0.0

resolution: workspace

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage_service: ^0.0.1
  meta: ^1.15.0
  quotify_utils: ^4.0.0

dev_dependencies:
  flutter_secure_storage: ^10.0.0-beta.4
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  password_strength: ^0.2.0
  lint: ^2.8.0
