name: quotes_repository
description: "A new Flutter package project."
version: 2.0.0

resolution: workspace

environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

dependencies:
  collection: ^1.19.0
  drift_database_service: ^3.0.0
  flutter:
    sdk: flutter
  meta: ^1.15.0
  quotify_utils: ^4.0.0
  tags_repository: ^1.0.0

dev_dependencies:
  faker: ^2.2.0
  flutter_test:
    sdk: flutter
  lint: ^2.8.0
