import 'privacy_data.dart';
import 'privacy_data_errors.dart';

/// [Exception]s related to [PrivacyData].
enum PrivacyDataModelErrors implements PrivacyDataErrors {
  /// Used when a [Map] is not conformed with the map generated by
  /// [PrivacyData] toMap extension.
  invalidMapFormat,

  /// Used when a [String] is not a correct json form of [PrivacyData].
  invalidJsonStringFormat,
}
