import 'privacy_data.dart';

/// [Exception]s related to [PrivacyData].
enum PrivacyDataErrors implements Exception {
  /// Used when a [Map] is not conformed with the map generated by
  /// [PrivacyData] toMap extension.
  invalidMapFormat,

  /// Used when a [String] is not a correct json form of [PrivacyData].
  invalidJsonStringFormat;
}
